{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ellmer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ellmer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ellmer/ellmer_{{ version }}.tar.gz
  sha256: d59a6d096e840362f8bc7f7e67cd7df5b8263578efdc8d73f2b70ac5213f2d67

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-s7 >=0.2.0
    - r-cli
    - r-coro >=1.1.0
    - r-glue
    - r-httr2 >=1.2.1
    - r-jsonlite
    - r-later >=1.4.0
    - r-lifecycle
    - r-promises >=1.3.1
    - r-rlang >=1.1.0
  run:
    - r-base
    - r-r6
    - r-s7 >=0.2.0
    - r-cli
    - r-coro >=1.1.0
    - r-glue
    - r-httr2 >=1.2.1
    - r-jsonlite
    - r-later >=1.4.0
    - r-lifecycle
    - r-promises >=1.3.1
    - r-rlang >=1.1.0

test:
  commands:
    - $R -e "library('ellmer')"           # [not win]
    - "\"%R%\" -e \"library('ellmer')\""  # [win]

about:
  home: https://ellmer.tidyverse.org, https://github.com/tidyverse/ellmer
  license: MIT
  summary: Chat with large language models from a range of providers including 'Claude' <https://claude.ai>, 'OpenAI' <https://chatgpt.com>, and more. Supports streaming, asynchronous calls, tool calling, and structured data extraction.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
